os: linux
dist: trusty

# We set language to Node.js (JavaScript) for the sake
# of making creating utility scripts later on easier.
language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

before_script:
  # Install yarn dependencies
  - "cd web && yarn install && cd .."

script:
  # Build Vue application
  - "cd web && yarn run build && cd .."
